# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanish_content', '0009_auto_20170304_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='link',
            field=models.URLField(blank=True, help_text='Please enter a link for learn more button', null=True),
        ),
    ]
