# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanish_content', '0010_auto_20170304_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduprogram',
            name='video',
            field=models.BooleanField(default=False),
        ),
    ]
