# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_auto_20170304_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='link2',
            field=models.URLField(blank=True, help_text='Please enter a link for learn more button', null=True),
        ),
    ]
