# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_auto_20170311_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='not required but helpful', max_length=20, null=True)),
                ('text', models.TextField(help_text='please enter the code for the embedded application here')),
            ],
        ),
    ]
